name: bbob_dart
description: A port of the bbcode parser and trasnformer [bbob](https://github.com/JiLiZART/bbob) in dart.
version: 0.0.1
# homepage: https://github.com/edwardez/bbob_dart
# author: Edward Zhang

environment:
  sdk: '>=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
